// Generated by `zfa package create-plugin` — envelope contract tests.
import 'dart:async';

import 'package:test/test.dart';
import 'package:zuraffa_ocr_platform/zuraffa_ocr_platform.dart';

class _Typed implements Exception {
  final String code;

  const _Typed(this.code);
}

class _EnvelopeFailure implements Exception {
  final String code;
  final String message;
  final bool recoverable;

  const _EnvelopeFailure(this.code, this.message, {required this.recoverable});
}

void main() {
  Exception typedFactory(
    String code,
    String message, {
    required bool recoverable,
  }) =>
      _EnvelopeFailure(code, message, recoverable: recoverable);

  group('PlatformOcrEnvelope', () {
    test('decodes success payloads', () async {
      final envelope = PlatformOcrEnvelope(
        invoke: (_, __) async => {'supported': true},
        onTyped: typedFactory,
      );

      expect(
        await envelope.call('isSupported', const {}),
        {'supported': true},
      );
    });

    test('native error payloads surface through the taxonomy', () async {
      final envelope = PlatformOcrEnvelope(
        invoke: (_, __) async => {
          'error': {'code': 'not_supported', 'message': 'no engine'},
        },
        onTyped: typedFactory,
        mapNativeError: (code, message) => _Typed(code),
      );

      await expectLater(
        envelope.call('isSupported', const {}),
        throwsA(isA<_Typed>().having((e) => e.code, 'code', 'not_supported')),
      );
    });

    test('unmapped native codes fall through to the adapter factory',
        () async {
      final envelope = PlatformOcrEnvelope(
        invoke: (_, __) async => {
          'error': {'code': 'weird', 'message': 'unexpected'},
        },
        onTyped: typedFactory,
      );

      await expectLater(
        envelope.call('isSupported', const {}),
        throwsA(
          isA<_EnvelopeFailure>()
              .having((e) => e.code, 'code', 'weird')
              .having((e) => e.recoverable, 'recoverable', isFalse),
        ),
      );
    });

    test('a past-timeout call surfaces as the typed recoverable timeout',
        () async {
      final envelope = PlatformOcrEnvelope(
        invoke: (_, __) => Completer<Map<String, Object?>>().future,
        onTyped: typedFactory,
        timeout: const Duration(milliseconds: 20),
      );

      await expectLater(
        envelope.call('isSupported', const {}),
        throwsA(
          isA<_EnvelopeFailure>()
              .having((e) => e.code, 'code', 'timeout')
              .having((e) => e.recoverable, 'recoverable', isTrue),
        ),
      );
    });

    test('non-map payloads surface as malformed_response', () async {
      final envelope = PlatformOcrEnvelope(
        invoke: (_, __) async => [1, 2, 3],
        onTyped: typedFactory,
      );

      await expectLater(
        envelope.call('batch', const {}),
        throwsA(
          isA<_EnvelopeFailure>()
              .having((e) => e.code, 'code', 'malformed_response'),
        ),
      );
    });

    test('adapter-typed failures thrown by the transport pass through',
        () async {
      final envelope = PlatformOcrEnvelope(
        invoke: (_, __) => throw const _Typed('already_typed'),
        onTyped: typedFactory,
        isTypedError: (error) => error is _Typed,
      );

      await expectLater(
        envelope.call('isSupported', const {}),
        throwsA(isA<_Typed>().having((e) => e.code, 'code', 'already_typed')),
      );
    });
  });
}
