// Generated by `zfa package create-plugin` — adapter test harness over a
// fake injected channel (success, taxonomy, timeout, unwired).
import 'dart:async';

import 'package:test/test.dart';
import 'package:zuraffa/zuraffa.dart';
import 'package:zuraffa_ocr/zuraffa_ocr.dart';
import 'package:zuraffa_ocr_ios/zuraffa_ocr_ios.dart';

void main() {
  group('IosOcrAdapter', () {
    test('isSupported decodes the native payload', () async {
      final channel = IosOcrChannel(
        invoke: (_, __) async => {'supported': true},
      );
      final port = IosOcrPort(channel: channel);

      expect(await port.isSupported(), isTrue);
    });

    test('invoke success decodes values through the envelope', () async {
      final channel = IosOcrChannel(
        invoke: (method, args) async => {
          'values': [42],
        },
      );
      final port = IosOcrPort(channel: channel);

      final values = await port.invoke(
        id: 'demo',
        export: 'run',
        args: const [OcrI32(1)],
      );

      expect(values.single, isA<OcrI32>());
    });

    test('native error payloads surface as typed failures', () async {
      final channel = IosOcrChannel(
        invoke: (_, __) async => {
          'error': {'code': 'not_supported', 'message': 'no wasm engine'},
        },
      );

      await expectLater(
        channel.call('isSupported', const {}),
        throwsA(
          isA<IosOcrException>()
              .having((e) => e.code, 'code', 'not_supported')
              .having((e) => e.recoverable, 'recoverable', isTrue),
        ),
      );
    });

    test('timeout surfaces as the typed recoverable timeout', () async {
      final channel = IosOcrChannel(
        invoke: (_, __) => Completer<Map<String, Object?>>().future,
        timeout: const Duration(milliseconds: 20),
      );

      await expectLater(
        channel.call('isSupported', const {}),
        throwsA(
          isA<IosOcrException>()
              .having((e) => e.code, 'code', 'timeout'),
        ),
      );
    });

    test('without a wired channel registration stays safe and typed',
        () async {
      final getIt = GetIt.instance;
      await getIt.reset();
      registerIosOcrDependencies(getIt);

      final port = getIt<OcrPort>();
      await expectLater(
        port.isSupported(),
        throwsA(
          isA<IosOcrException>()
              .having((e) => e.code, 'code', 'channel_not_wired'),
        ),
      );
    });
  });
}
