// Generated by `zfa package create-plugin` — value codec contract.
import 'package:test/test.dart';
import 'package:zuraffa_ocr/zuraffa_ocr.dart';

void main() {
  test('i32 encodes to an int', () {
    expect(OcrI32(42).encode(), 42);
  });

  test('i64 encodes to a decimal string and decodes back', () {
    final value = OcrI64(BigInt.parse('9007199254740993'));

    expect(value.encode(), '9007199254740993');
    expect(
      (OcrValue.decode(value.encode()) as OcrI64).value,
      BigInt.parse('9007199254740993'),
    );
  });

  test('f64 encodes to a double', () {
    expect(OcrF64(0.5).encode(), 0.5);
  });
}
