// Generated by `zfa package create-plugin` — app-package test harness.
import 'dart:typed_data';

import 'package:test/test.dart';
import 'package:zuraffa/zuraffa.dart';
import 'package:zuraffa_ocr/zuraffa_ocr.dart';

class _RecordingPort implements OcrPort {
  final List<String> calls = [];

  @override
  Future<bool> isSupported() async {
    calls.add('isSupported');
    return true;
  }

  @override
  Future<OcrModule> compile({
    required String id,
    required Uint8List bytes,
  }) async {
    calls.add('compile:$id');
    return OcrModule(id: id, byteLength: bytes.lengthInBytes);
  }

  @override
  Future<List<OcrValue>> invoke({
    required String id,
    required String export,
    List<OcrValue> args = const [],
  }) async {
    calls.add('invoke:$id:$export');
    return [const OcrI32(42)];
  }

  @override
  Future<void> unload({required String id}) async {
    calls.add('unload:$id');
  }
}

void main() {
  group('OcrService', () {
    late _RecordingPort port;
    late OcrService service;

    setUp(() {
      port = _RecordingPort();
      service = OcrService(port: port);
    });

    test('compile registers the module and call routes through the port',
        () async {
      final module = await service.compile(
        id: 'demo',
        bytes: Uint8List.fromList([1, 2, 3]),
      );

      expect(module.byteLength, 3);
      expect(service.compiledModules, contains('demo'));

      final results = await service.call(
        id: 'demo',
        export: 'run',
        args: const [OcrI32(1)],
      );

      expect(port.calls, contains('invoke:demo:run'));
      expect(results.single, isA<OcrI32>());
      expect((results.single as OcrI32).value, 42);
    });

    test('call before compile surfaces the typed not_compiled failure',
        () async {
      await expectLater(
        service.call(id: 'missing', export: 'run'),
        throwsA(
          isA<OcrException>()
              .having((e) => e.code, 'code', 'not_compiled')
              .having((e) => e.recoverable, 'recoverable', isFalse),
        ),
      );
    });

    test('double compile surfaces already_compiled', () async {
      await service.compile(id: 'demo', bytes: Uint8List(0));

      await expectLater(
        service.compile(id: 'demo', bytes: Uint8List(0)),
        throwsA(
          isA<OcrException>()
              .having((e) => e.code, 'code', 'already_compiled'),
        ),
      );
    });

    test('unload releases the module and further calls fail typed',
        () async {
      await service.compile(id: 'demo', bytes: Uint8List(0));
      await service.unload(id: 'demo');

      expect(service.compiledModules, isNot(contains('demo')));
      await expectLater(
        service.call(id: 'demo', export: 'run'),
        throwsA(isA<OcrException>()),
      );
    });

    test('registration without a port surfaces typed port_not_wired',
        () async {
      final getIt = GetIt.instance;
      await getIt.reset();
      registerOcrDependencies(getIt);

      final service = getIt<OcrService>();
      await expectLater(
        service.supported(),
        throwsA(
          isA<OcrException>()
              .having((e) => e.code, 'code', 'port_not_wired'),
        ),
      );
    });

    test('registration with a port binds the service to it', () async {
      final getIt = GetIt.instance;
      await getIt.reset();
      registerOcrDependencies(getIt, port: _RecordingPort());

      expect(await getIt<OcrService>().supported(), isTrue);
    });
  });

  group('OcrValue', () {
    test('round-trips through the channel encoding', () {
      final i32 = OcrValue.decode(OcrI32(7).encode());
      expect(i32, isA<OcrI32>());

      final i64 = OcrValue.decode(
        OcrI64(BigInt.parse('9007199254740993')).encode(),
      );
      expect((i64 as OcrI64).value, BigInt.parse('9007199254740993'));

      final f64 = OcrValue.decode(OcrF64(1.5).encode());
      expect((f64 as OcrF64).value, 1.5);
    });

    test('rejects payloads it cannot decode', () {
      expect(
        () => OcrValue.decode(const [1, 2, 3]),
        throwsA(
          isA<OcrException>()
              .having((e) => e.code, 'code', 'malformed_value'),
        ),
      );
    });
  });
}
